name: Deploy
on:
    push:
        branches:
            - master
jobs:
    test:
        environment: dev
        env:
            MONGODB_USER: ${{ secrets.MONGODB_USER}}
        runs-on: windows-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Get Node
              uses: actions/setup-node@v4
            - name: Install dependencies
              run: npm ci
            - name: Deploy
              run: echo "${{ env.MONGODB_USER }}"